name: Deploy to AWS

# Trigger the workflow when there is a push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest   # You can choose the OS for your runner (e.g., Ubuntu)

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment (you can choose your Python version)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Step 3: Install the required dependencies for your project
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Deploy to AWS Lambda
    - name: Deploy to AWS Lambda
      run: |
        # Configure AWS CLI with secrets stored in GitHub
        aws configure set aws_access_key_id ${{ secrets.AKIAYKGIRZ3TRWR2GU43 }}
        aws configure set aws_secret_access_key ${{ secrets.aWRKYjGN0wqAL2gUVZxfgc+6y0BU36AwIDsN/Zi4}}
        aws configure set default.region us-east-1

        # Update the Lambda function code
        aws lambda update-function-code --function-name PagerDutySlackIntegratio --zip-file fileb://BOT.zip
